apiVersion: batch/v1
kind: Job
metadata:
  name: certgen-leaves
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: certgen
          image: alpine
          command:
            - /certgen/bin/certgen
            - leaves
          volumeMounts:
            - name: certs
              mountPath: /certgen/certs
            - name: scripts
              mountPath: /certgen/bin
      restartPolicy: Never
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0700
