apiVersion: batch/v1
kind: CronJob
metadata:
  name: certgen
spec:
  # schedule: "0 0 1 * *" # Rotate monthly
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: generate-leaf-certs
              image: alpine
              command:
                - /certgen/bin/certgen
                - leaves
              volumeMounts:
                - name: certs
                  mountPath: /certgen/certs
                - name: scripts
                  mountPath: /certgen/bin
            - name: restart-backstage
              image: bitnami/kubectl:latest
              command:
                - kubectl
                - rollout
                - restart
                - deployments/backstage
              volumeMounts:
                - name: certs
                  mountPath: /certgen/certs
                - name: scripts
                  mountPath: /certgen/bin
            - name: wait-for-backstage
              image: bitnami/kubectl:latest
              command:
                - kubectl
                - rollout
                - status
                - deployments/backstage
                - --watch=true
              volumeMounts:
                - name: certs
                  mountPath: /certgen/certs
                - name: scripts
                  mountPath: /certgen/bin
            - name: restart-postgres
              image: bitnami/kubectl:latest
              command:
                - kubectl
                - rollout
                - restart
                - statefulsets/backstage-postgres
              volumeMounts:
                - name: certs
                  mountPath: /certgen/certs
                - name: scripts
                  mountPath: /certgen/bin
          containers:
            - name: noop
              image: alpine
              command:
                - echo
                - "done rotating certs"
          restartPolicy: Never
          volumes:
            - name: certs
              persistentVolumeClaim:
                claimName: certs
            - name: scripts
              configMap:
                name: scripts
                defaultMode: 0700
                items:
                  - key: certgen
                    path: certgen
