apiVersion: batch/v1
kind: Job
metadata:
  name: certgen-root
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      containers:
        - name: certgen
          image: alpine
          command:
            - /certgen/bin/certgen
            - root
          volumeMounts:
            - name: certs
              mountPath: /certgen/certs
            - name: scripts
              mountPath: /certgen/bin
      restartPolicy: Never
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0700
            items:
              - key: certgen
                path: certgen
