apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  certgen: |
{{ tpl (.Files.Get "files/certgen.sh.tpl") . | indent 4 }}
