apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql_conf: |
    listen_addresses = '*'
    hba_file = '/var/lib/postgresql/config/pg_hba.conf'
    ssl = on
    ssl_ca_file = '/certs/root.crt'
    ssl_cert_file = '/certs/server.crt'
    ssl_key_file = '/certs/server.key'
  pg_hba_conf: |
    # TYPE   DATABASE     USER       ADDRESS       METHOD
    local    all          postgres                 peer
    hostssl  all          all        all           cert
  init_user: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER backstage;
    EOSQL
