{{- $supass := (randAlphaNum 16) -}}
{{- $pass := (randAlphaNum 16) -}}
apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres
type: Opaque
immutable: true
stringData:
  supassword: {{ $supass | quote }}
  password: {{ $pass | quote }}
  pgpass: {{ (printf "postgres:%s\nbackstage:%s" $supass $pass) | quote }}
