apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backstage-postgres
  labels:
    app: backstage
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
      role: db
  serviceName: backstage-postgres
  template:
    metadata:
      labels:
        app: backstage
        role: db
    spec:
      # terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 999 # postgres
        runAsGroup: 999 # postgres
      containers:
        - name: backstage-postgres
          image: "postgres:{{ .Chart.AppVersion }}"
          args: ["-c", "config_file=/var/lib/postgresql/config/postgresql.conf"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pg
          volumeMounts:
            - name: postgres-config
              mountPath: /var/lib/postgresql/config
            - name: backstage-postgres-data
              mountPath: /var/lib/postgresql/data
            - name: certs
              mountPath: /certs
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
            items:
              - key: postgresql_conf
                path: postgresql.conf
              - key: pg_hba_conf
                path: pg_hba.conf
        - name: backstage-postgres-data
          persistentVolumeClaim:
            claimName: backstage-postgres-data
        - name: certs
          persistentVolumeClaim:
            claimName: certs
  volumeClaimTemplates:
    - metadata:
        name: backstage-postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
