apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # TODO: hardcoded values
  document: |
    app:
      title: Frontside Backstage
      baseUrl: "http://localhost:3000"
    organization:
      name: Frontside
    backend:
      baseUrl: "http://localhost:7000"
      listen:
        port: 7000
      database:
        client: pg
        connection:
          host: backstage-postgres
          port: 5432
          user: postgres
          password:
            $file: /config/pg/pass.txt
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: "*"
        methods: [GET, POST, PUT, DELETE]
        credentials: true
    auth:
      providers: {}
    techdocs:
      builder: 'local'
      generators:
        techdocs: 'docker'
      publisher:
        type: 'local'
    catalog:
      rules:
        - allow: [Component, System, API, Group, User, Template, Location]
      locations:
        - type: file
          target: "./random-word-config.yaml"
        - type: file
          target: "./backstage-backend-config.yaml"
        - type: file
          target: "./backstage-postgres-config.yaml"
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: 'https://kubernetes.default.svc'
              name: microk8s-cluster
              authProvider: serviceAccount
              serviceAccountToken:
                $file: /config/sa/token.txt
