apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  labels:
    app: backstage
    role: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
      role: service
  template:
    metadata:
      labels:
        app: backstage
        role: service
    spec:
      serviceAccountName: backstage
      # initContainers:
      #   - name: debug
      #     image: ubuntu
      #     command:
      #       - sleep
      #       - "999999999"
      #     volumeMounts:
      #       - name: certs
      #         mountPath: /config/certs
      containers:
        - name: backstage
          image: backstage
          imagePullPolicy: IfNotPresent
          # securityContext:
          #   runAsNonRoot: true
          #   runAsUser: 999 # backstage
          #   runAsGroup: 999 # backstage
          env:
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: app-config
              mountPath: /config/app
            - name: service-account-config
              mountPath: /config/sa
            - name: certs
              mountPath: /config/certs
      volumes:
        - name: app-config
          configMap:
            name: app-config
            items:
              - key: document
                path: app-config.yaml
        - name: service-account-config
          secret:
            secretName: backstage
            items:
              - key: token
                path: token.txt
                mode: 0644
        - name: certs
          persistentVolumeClaim:
            claimName: certs
