apiVersion: v1
kind: Service
metadata:
  name: backstage
  labels:
    app: backstage
    role: service
spec:
  type: NodePort
  selector:
    app: backstage
    role: service
  ports:
    - name: http
      port: 7000
